GeneralConfig: {WorkingMemory.maximum.size: '5000000', herour.logger.levels: '[''ERROR'',
    ''WARN'']', stack.url: 'http://172.16.1.192/?qa=', Multiinstance.maximum.size: '50',
  general.enum.packages: com.fanap.demo.enums, JsonProcessMemory.maximum.size: '10000000',
  log.path: config/log4j.properties, root.logger.level: '', load.default.log.config: 'false'}
